### ISSUE TITLE
Getting 301 errors since end of March

### ISSUE THREAD

**Issue by huubvanh** [grapeot/IFTTTDelay#6]
Hi, I use your great delay webhook function for home automation but face an issue since end of March.

In the logging of my ifttt applet when posting a new delay I can see a 301 error.
When I just call the URL via postman its okay.

Is this a known issue/bug or did I miss an update to apply in my applet?

Thanks in advance for the reply!

**Comment by grapeot** [comment]
Thanks for reporting this! I upgraded my server in the end of March and that's probably the reason of why you saw a 301. But a 301 is not really an error. It's telling the browser that the page has been permanently moved and requesting the browser to follow the redirection. From the backend I don't see a drop on the success rate but I may be missing something. Curious did you see the action being executed after the delay? I guess not? Did you use an http or an https endpoint? If it's the former, I may know what is the reason and will help change the server configuration. If it's the latter, I will need to do more investigation.

Thanks,
Yan

________________________________
From: huubvanh ***@***.***>
Sent: Saturday, April 9, 2022 00:50
To: grapeot/IFTTTDelay ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [grapeot/IFTTTDelay] Getting 301 errors since end of March (Issue #6)


Hi, I use your great delay webhook function for home automation but face an issue since end of March.

In the logging of my ifttt applet when posting a new delay I can see a 301 error.
When I just call the URL via postman its okay.

Is this a known issue/bug or did I miss an update to apply in my applet?

Thanks in advance for the reply!

**Comment by huubvanh** [comment]
Hi, thanks for the quick response! In the first applet I turn on ventilation and as final action register the delay via: 
https://lab.grapeot.me/ifttt/delay?event=VentOff90Min&t=90&key=mykey

![Screenshot_20220410-071407](https://user-images.githubusercontent.com/103306489/162602494-5e325a5d-9a33-4e5d-a290-f0b8e688d9e9.png)

**Comment by grapeot** [comment]
Ah this is very helpful. This is because I upgraded the security settings in the end of March to enforce https. And when one visits the old `http` URL, the browser will receive a 301 so it knows to automatically redirect to the `https` URL. It seems to work with most of the IFTTT requests according to my monitoring after the upgrade, but looks it may fail the IFTTT in some cases. In your case, can you change the `http` in your URL to `https`? So it would look like this: `https://lab.grapeot.me/ifttt/delay?event=VentOff90Min&t=90&key=mykey`. (Your comment shows `https` but the screenshot shows `http`. So I assume the comment may actually be `http`.)

**Comment by huubvanh** [comment]
Sorry, I changed to https and its working again. Sorry for waisting your time.
Best regards, Huub

**Comment by grapeot** [comment]
Glad to see it's resolved! No no no it's not wasting my time at all. Thanks for letting me know the problem and putting it as a GitHub issue. So others may also benefit from it.
________________________________
